/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package agentravel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author LENOVO
 */
public class jKelolaPembayaranAdmin extends javax.swing.JPanel {

    /**
     * Creates new form jKelolaPembayaranAdmin
     */
    public jKelolaPembayaranAdmin() {
        initComponents();
        txtKodeTiket.setEditable(false);
        txtNamaUser.setEditable(false);
        txtBus.setEditable(false);
        txtRute.setEditable(false);
        txtTotalBayar.setEditable(false);
        
        loadDataPembayaran();
        setupTableListener();
        
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaruiStatus();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNamaUser = new javax.swing.JTextField();
        txtBus = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        txtKodeTiket = new javax.swing.JTextField();
        txtRute = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKelolaPembayaran = new javax.swing.JTable();
        btnPerbarui = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(230, 242, 221));

        jPanel3.setBackground(new java.awt.Color(136, 189, 164));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KELOLA PEMBAYARAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(177, 211, 185));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verifikasi Pembayaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 18), new java.awt.Color(101, 146, 135))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(653, 208));

        txtTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBayarActionPerformed(evt);
            }
        });

        txtKodeTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeTiketActionPerformed(evt);
            }
        });

        txtRute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Tiket");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terverifikasi", "Tidak Terverifikasi", " " }));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama User");

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TOTAL BAYAR");

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RUTE");

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BUS");

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("STATUS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaUser)
                            .addComponent(txtBus))
                        .addGap(52, 52, 52)
                        .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtRute, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRute, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBus, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cmbStatus))
                .addContainerGap())
        );

        tblKelolaPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Tiket", "Nama User", "Bus", "Rute", "Total Bayar", "Metode Pembayaran", "Status"
            }
        ));
        tblKelolaPembayaran.setPreferredSize(new java.awt.Dimension(653, 208));
        jScrollPane1.setViewportView(tblKelolaPembayaran);

        btnPerbarui.setBackground(new java.awt.Color(255, 236, 153));
        btnPerbarui.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnPerbarui.setForeground(new java.awt.Color(255, 255, 255));
        btnPerbarui.setText("PERBARUI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(btnPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataPembayaran() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"Kode Tiket", "Nama User", "Bus", "Rute", "Total Bayar", "Metode Pembayaran", "Status"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            Connection conn = AgenTravel.getKoneksi();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database tidak tersedia!");
                return;
            }
            String sql = "SELECT p.kode_tiket, u.nama AS nama_user, b.nama_bus, j.asal, j.tujuan, "
                       + "p.total_bayar, p.metode_pembayaran, p.status "
                       + "FROM pemesanan p "
                       + "JOIN users u ON p.user_id = u.id "
                       + "JOIN jadwal j ON p.jadwal_id = j.id "
                       + "JOIN bus b ON j.bus_id = b.id "
                       + "ORDER BY p.created_at DESC";
            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            NumberFormat nf = NumberFormat.getNumberInstance(new Locale("id", "ID"));

            while (rs.next()) {
                String rute = rs.getString("asal") + " - " + rs.getString("tujuan");
                double total = rs.getDouble("total_bayar");
                String status = rs.getString("status");
                if (status == null || status.trim().isEmpty()) {
                    status = "Belum Terverifikasi";
                }
                model.addRow(new Object[]{
                    rs.getString("kode_tiket"),
                    rs.getString("nama_user"),
                    rs.getString("nama_bus"),
                    rute,
                    "Rp " + nf.format(total),
                    rs.getString("metode_pembayaran"),
                    status
                });
            }

            tblKelolaPembayaran.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data pembayaran: " + e.getMessage());
        }
    }

    private void setupTableListener() {
        tblKelolaPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tblKelolaPembayaran.getSelectedRow();
                if (row >= 0) {
                    txtKodeTiket.setText(tblKelolaPembayaran.getValueAt(row, 0).toString());
                    txtNamaUser.setText(tblKelolaPembayaran.getValueAt(row, 1).toString());
                    txtBus.setText(tblKelolaPembayaran.getValueAt(row, 2).toString());
                    txtRute.setText(tblKelolaPembayaran.getValueAt(row, 3).toString());
                    txtTotalBayar.setText(tblKelolaPembayaran.getValueAt(row, 4).toString());
                    
                    String status = tblKelolaPembayaran.getValueAt(row, 6).toString();
                    if ("Terverifikasi".equalsIgnoreCase(status)) {
                        cmbStatus.setSelectedItem("Terverifikasi");
                    } else if ("Tidak Terverifikasi".equalsIgnoreCase(status)) {
                        cmbStatus.setSelectedItem("Tidak Terverifikasi");
                    } else {
                        cmbStatus.setSelectedItem(" ");
                    }
                }
            }
        });
    }

    private void perbaruiStatus() {
        String kodeTiket = txtKodeTiket.getText().trim();
        if (kodeTiket.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi pembayaran terlebih dahulu dari tabel!");
            return;
        }

        String statusBaru = cmbStatus.getSelectedItem().toString();
        
        Connection conn = AgenTravel.getKoneksi();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Koneksi database tidak tersedia!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin memperbarui status pembayaran tiket " + kodeTiket + " menjadi '" + statusBaru + "'?",
            "Konfirmasi Perbarui Status", JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            conn.setAutoCommit(false);

            // 1. Update status pemesanan
            String sqlUpdatePesan = "UPDATE pemesanan SET status = ? WHERE kode_tiket = ?";
            try (PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdatePesan)) {
                pstUpdate.setString(1, statusBaru);
                pstUpdate.setString(2, kodeTiket);
                pstUpdate.executeUpdate();
            }

            // 2. Dapatkan pemesanan_id
            int pemesananId = -1;
            String sqlPemesananId = "SELECT id FROM pemesanan WHERE kode_tiket = ?";
            try (PreparedStatement pstId = conn.prepareStatement(sqlPemesananId)) {
                pstId.setString(1, kodeTiket);
                try (ResultSet rsId = pstId.executeQuery()) {
                    if (rsId.next()) {
                        pemesananId = rsId.getInt("id");
                    }
                }
            }

            if (pemesananId != -1) {
                // 3. Jika status baru adalah "Tidak Terverifikasi", lepas kursi (kembalikan ke 'Tersedia')
                //    Jika status baru adalah "Terverifikasi" atau lainnya, set status kursi ke 'Dipesan'
                String statusKursi = "Tidak Terverifikasi".equalsIgnoreCase(statusBaru) ? "Tersedia" : "Dipesan";
                
                String sqlUpdateKursi = "UPDATE kursi k "
                                      + "JOIN detail_pemesanan dp ON k.id = dp.kursi_id "
                                      + "SET k.status = ? "
                                      + "WHERE dp.pemesanan_id = ?";
                try (PreparedStatement pstKursi = conn.prepareStatement(sqlUpdateKursi)) {
                    pstKursi.setString(1, statusKursi);
                    pstKursi.setInt(2, pemesananId);
                    pstKursi.executeUpdate();
                }
            }

            conn.commit();
            JOptionPane.showMessageDialog(this, "Status pembayaran berhasil diperbarui!");
            clearForm();
            loadDataPembayaran();

        } catch (SQLException ex) {
            try {
                conn.rollback();
            } catch (SQLException ignored) {}
            JOptionPane.showMessageDialog(this, "Gagal memperbarui status pembayaran: " + ex.getMessage());
        } finally {
            try {
                conn.setAutoCommit(true);
            } catch (SQLException ignored) {}
        }
    }

    private void clearForm() {
        txtKodeTiket.setText("");
        txtNamaUser.setText("");
        txtBus.setText("");
        txtRute.setText("");
        txtTotalBayar.setText("");
        cmbStatus.setSelectedIndex(2); // Set ke default " "
    }

    private void txtTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBayarActionPerformed

    private void txtKodeTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeTiketActionPerformed

    private void txtRuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKelolaPembayaran;
    private javax.swing.JTextField txtBus;
    private javax.swing.JTextField txtKodeTiket;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JTextField txtRute;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
